# Generated by Django 4.0.2 on 2022-05-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_saveslot_player'),
        ('users', '0002_alter_profile_active_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.saveslot'),
        ),
    ]
