# Generated by Django 4.0.2 on 2022-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_saveslot_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveslot',
            name='slot_id',
            field=models.IntegerField(default=1),
        ),
    ]
