# Generated by Django 4.0.2 on 2022-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_saveslot_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveslot',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
